name: Build APK

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the job

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java Development Kit (JDK)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Ensure this matches your project's requirements

    # Step 3: Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: 'commandlinetools;latest'  # Use the latest command line tools version

    # Step 4: Install NDK
    - name: Install Android NDK r22
      run: |
        yes | sdkmanager --licenses
        sdkmanager "ndk;22.1.7171670"  # Install the specified version of the NDK

    # Step 5: Build the APK
    - name: Build APK
      run: ./gradlew assembleRelease  # Use the appropriate Gradle task for your build configuration

    # Step 6: Upload APK as an artifact (optional)
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk  # Adjust path as needed
